# docker-compose.yml (Versión Definitiva con EasyOCR)
services:
  # --- Servicio de la Base de Datos de Odoo ---
  db:
    image: postgres:15
    container_name: odoo_db
    environment:
      - POSTGRES_USER=odoo
      # ¡USA TU CONTRASEÑA SEGURA!
      - POSTGRES_PASSWORD=v6gz5x5EmA726O7
      - POSTGRES_DB=postgres
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
    restart: always

  # --- Servicio de Odoo ---
  odoo:
    image: odoo:19.0
    container_name: odoo_web
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      - HOST=db
      - USER=odoo
      # ¡DEBE COINCIDIR CON LA DE ARRIBA!
      - PASSWORD=v6gz5x5EmA726O7
      
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
    restart: always
    
volumes:
  odoo-db-data:
  odoo-web-data: